### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-tooltips#2]
- [x] have a prop to display a beacon using the portal (`wrapperOptions`)
- [ ] ~~render a transparent overlay that catches outside clicks and closes the tooltip~~
- [ ] ~~hide on scroll~~
- [ ] ~~close tooltip by clicking on itself~~

In case you need any of these, use a controlled tooltip and handle scrolling on the host app

**Comment by romanlex** [comment]
maybe for overlay use https://github.com/kentor/react-click-outside?

**Comment by gilbarbara** [comment]
I'm thinking that these functionalities should be added by the app itself in the controlled mode.

Adding all these would increase this library footprint and most users wouldn't use most of these features. Bloatware feelings.

**Comment by mplungjan** [comment]
How to place the clickable beacon/span relative to the target of the tooltip

E.g. I have

tab(?)------------tab(?)-------------tab(?)

component(?)

component(?)

and I want somewhere in the application to have

```
  <Tooltip
      content='This is the tab1'
      target='.tab>.tab1'
    >
        <span>(?)</span>
    </Tooltip>
  <Tooltip
      content='This is the tab2'
      target='.tab>.tab2'
    >
        <span>(?)</span>
    </Tooltip>
    <Tooltip
      content='This is component 1'
      target='#component1'
    >
        <span>(?)</span>
    </Tooltip>



```
