### ISSUE TITLE
Recalc position inside custom scrollable component?

### ISSUE THREAD

**Issue by romanlex** [gilbarbara/react-tooltips#24]
![image](https://user-images.githubusercontent.com/3369304/36220289-19393b56-11cb-11e8-8d35-a8453061db5a.png)
Hello, I have little bug when trying add tooltip to custom scrollable component(( when I trying to scroll inside pane I have fixed position for my tooltip(

**Comment by romanlex** [comment]
this codebox show bug 
https://codesandbox.io/s/r7942xp8nq

**Comment by romanlex** [comment]
This is bug in scrollbar component. I'm trying use another and all work properly
https://codesandbox.io/s/7yx7l063m0

**Comment by gilbarbara** [comment]
I think this behavior is related to this [issue](https://github.com/FezVrasta/popper.js/pull/527) on popper.js

I'll try to check this later. But at first, popper.js supports different scroll parents.

**Comment by romanlex** [comment]
What you think about last codesandbox? Why all work properly?

**Comment by gilbarbara** [comment]
Ok, closing this since it works with other implementations.

Why does it work with different components? Probably the way the first component handled scrolling or a scroll listener that stop the event bubbling. ¯\_(ツ)_/¯

**Comment by gilbarbara** [comment]
btw, you don't need to set the `target` prop for the button used as children.

**Comment by gilbarbara** [comment]
And with these edge cases, you can always use the controlled mode and add a listener to the scrolling element and hide the tooltip by yourself when it scrolls.

**Comment by romanlex** [comment]
```target``` it is randomness, the results of experiments)
