### ISSUE TITLE
After upgrade tooltip is broken

### ISSUE THREAD

**Issue by romanlex** [gilbarbara/react-tooltips#30]
After upgrade from 0.4.1 to 0.4.2 or higher tooltip is broken
![image](https://user-images.githubusercontent.com/3369304/37273887-1ace4300-25ec-11e8-83ce-004e75c6e484.png)
React 15.6

**Comment by gilbarbara** [comment]
As usual, post your configuration and reproducible example.
The demo is working with 0.4.5: https://codesandbox.io/s/84vn36m178

**Comment by romanlex** [comment]
https://codesandbox.io/s/7mv9122kjj
If you trying remove all components with tooltip, all work perfectly

**Comment by gilbarbara** [comment]
It's a React 15 problem.
I'll check into it

**Comment by gilbarbara** [comment]
Fixed in 0.4.6
React can't render arrays so I need to wrap the `children` with an element...

Thanks
